### ISSUE TITLE
Start-NessusScan parameter AlternateTarget not working

### ISSUE THREAD

**Issue by mg07647** [tenable/Posh-Nessus#4]
At least not for me. We have Nessus v6.4.3. When I try this from the server's built-in API tester it works fine, but not from Powershell. It uses the IP already in the scan not the alternate. Some searching indicated it may require a comma or a line feed as a terminator, but I tried modifying Scan.ps1 with all combinations and couldn't get any to work.

**Comment by michaeltlombardi** [comment]
Is this problem still existent?

**Comment by leunammejii** [comment]
I'm having the same issue. Since new machines are created daily, I need to be able to dynamically pull IP addresses and POC information from Solarwinds and email the result to each POC. Since there are multiple POCs on each subnet, it's not as simple as scanning just the subnet and sending the email to one person. I chose PowerShell over Python because I can automate it with a secure PSCredential object. Has anyone taken a look at this?

**Comment by darkoperator** [comment]
Will take a look at the issue can I get the version of PowerShell you are using and version of Windows?

**Comment by mg07647** [comment]
I'm using PSVersion 4.0, Windows 7 x64.

**Comment by leunammejii** [comment]
PSVersion 5.0, Windows 7 x64

**Comment by darkoperator** [comment]
Just pushed an update to Github , can you test and see if it fixes the issue?

**Comment by leunammejii** [comment]
It works! That is insane though. While debugging yesterday, I added the content-type to the RestMethodParams hash table in Posh-Nessus.psm1 to be included in the body instead of passing in the parameter and failed. I must have typed something wrong. Thanks again.

**Comment by mg07647** [comment]
Works for me also. Thanks!
